---
title: "Applying Random Forest Methods on Predictors for Diabetes"
# author: 
# - name: "Danielle Novinski"
# - name: "Victor Richerson"
# - name: "Dinh Do"
#date: '`r Sys.Date()`'
format: 
  revealjs:
    slide-number: true
    transition: slide
self-contained: true
execute: 
  warning: false
  message: false
---

## Introduction to Random Forest
- Random forest is an ensemble learning method composed of multiple decision trees.
- Random forest is used in a variety of applications such as ecology, medicine, astronomy, agriculture, traffic, and bioinformatics.
- Random forest improves on the decision tree method for classification (predicting a class label) and regression (predicting a continuous value).


## Variable Selection
- We seek to reduce the number of survey questions (and variables) and focus on the most influential predictors of diabetes.
- We accomplished this by calculating the variable importance using the Gini impurity value.
- The most important variables impacting Diabetes were found to be BMI,
General Health, High Blood Pressure, Age, Income, and Physical Health.



